name: image builder
# description: "Build image-builder image for image-builder application."
on:
  push:
    branches:
      - main

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: image-builder
      dockerfile: Dockerfile
      context: .