name: image builder
# description: "Build image-builder image for image-builder application."
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: ip-auth
      dockerfile: Dockerfile
      context: .
      tags: |
        ghcr.io/kyma-project/ip-auth:latest
        ghcr.io/kyma-project/ip-auth:${{ github.ref_name }}