name: pull-build-test-out-org.yml
#  description: Build image for rotate-service-account
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/cloud-run/rotate-service-account/Dockerfile"
      - "cmd/cloud-run/rotate-service-account/*.go"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: ip-auth
      dockerfile: Dockerfile
      context: .